reorder_imports = true
max_width = 120
edition = "2021"
hard_tabs = true
format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
